# Generated by Django 5.0.6 on 2024-06-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file_path',
            field=models.FileField(upload_to='certificates/'),
        ),
    ]
